#!/bin/sh

date '+%a, %b %d  %H:%M '

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" ;;
	3) pgrep -x dunst >/dev/null && notify-send "📅 Time/date module" "Left click shows the current month." ;;
esac
